import { auth } from "@/platform/auth/auth";
import { getActivePerson } from "@/platform/auth/match-person";
import { can } from "@/platform/rbac/engine";
import { getObject } from "@/platform/storage";
import { contentDisposition } from "@/platform/content-disposition";
import { log } from "@/platform/logging";
import { getContractHipaa } from "@/modules/recruitment/services/onboarding";
import { INLINE_SAFE_MIME_TYPES } from "@/modules/recruitment/services/file-preview";

type RouteContext = { params: Promise<{ contractId: string }> };

// hipaaStoredName is generated by submitContract as `hipaa-<uuid>[.ext]`. Only a
// value in that exact shape may be joined into a storage key, so a malformed or
// injected name can never escape the contract's `onboarding/<id>/` prefix.
const STORED_NAME_RE = /^hipaa-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(\.[A-Za-z0-9]{1,8})?$/;

/**
 * GET /api/recruitment/onboarding/[contractId]/hipaa
 *
 * Serves the HIPAA certificate an applicant uploaded on their onboarding
 * contract, gated to the reviewers who may see the signed-contract page.
 * Route handlers cannot redirect(), so auth failures return JSON.
 *
 * Security:
 *   - Requires a session matched to an active Person.
 *   - Authorization mirrors the signed-contract page: recruitment.access +
 *     recruitment.review_all (SRR). review_all is global, so there is no
 *     per-cycle scoping to enforce here.
 *   - The storage key is the contract's own id plus a server-generated
 *     storedName, validated against STORED_NAME_RE -- no path traversal.
 *   - Both "not allowed" and "missing" return 404, so a viewer cannot tell an
 *     existing certificate from one they may not see.
 */
export async function GET(request: Request, context: RouteContext): Promise<Response> {
  const session = await auth();
  if (!session?.personId) return Response.json({ error: "Unauthorized" }, { status: 401 });
  const activePerson = await getActivePerson(session.personId);
  if (!activePerson) return Response.json({ error: "Unauthorized" }, { status: 401 });

  const [hasAccess, canReview] = await Promise.all([
    can(activePerson.id, "recruitment.access"),
    can(activePerson.id, "recruitment.review_all"),
  ]);

  const { contractId } = await context.params;
  const meta = hasAccess && canReview ? await getContractHipaa(contractId) : null;
  if (!meta?.hipaaStoredName) return Response.json({ error: "Not found" }, { status: 404 });
  if (!STORED_NAME_RE.test(meta.hipaaStoredName)) {
    return Response.json({ error: "Not found" }, { status: 404 });
  }

  const buf = await getObject(`onboarding/${contractId}/${meta.hipaaStoredName}`);
  if (!buf) {
    log.error("[onboarding/hipaa] certificate missing in storage", { contractId, storedName: meta.hipaaStoredName });
    return Response.json({ error: "Not found" }, { status: 404 });
  }
  // Copy into a standalone Uint8Array (a valid BodyInit) so the Response owns
  // bytes independent of the source Buffer's backing store.
  const fileBytes = new Uint8Array(buf);
  const fileByteLength = buf.byteLength;

  const mimeType = meta.hipaaMimeType ?? "application/octet-stream";
  // `?inline=1` previews in-page; the default is a download. Inline rendering is
  // gated to a safe mime allowlist so a maliciously-typed file can never execute
  // script in our origin.
  const inline = new URL(request.url).searchParams.get("inline") === "1";
  const renderInline = inline && INLINE_SAFE_MIME_TYPES.has(mimeType);

  return new Response(fileBytes, {
    status: 200,
    headers: {
      "Content-Type": mimeType,
      "Content-Disposition": contentDisposition(meta.hipaaFileName ?? "hipaa-certificate", { inline: renderInline }),
      "Content-Length": String(fileByteLength),
      // Defense in depth: never sniff a different type than declared, and deny the
      // served document any ability to load or execute sub-resources.
      "X-Content-Type-Options": "nosniff",
      "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'",
    },
  });
}
