-- CreateEnum
CREATE TYPE "ReferralType" AS ENUM ('EDUCATION', 'MDIC');

-- CreateEnum
CREATE TYPE "ReferralPurpose" AS ENUM ('NEW_FC', 'RENEW_FC', 'HUSKY', 'EDUCATION_SESSION');

-- CreateEnum
CREATE TYPE "ReferralUrgency" AS ENUM ('ROUTINE', 'URGENT', 'STAT');

-- CreateEnum
CREATE TYPE "ReferralState" AS ENUM ('ENTERED', 'AWAITING_FC', 'SCHEDULED', 'COMPLETED', 'CANCELLED_BY_PROVIDER', 'CANCELLED_OR_NO_SHOW', 'CLOSED_DECLINED');

-- CreateEnum
CREATE TYPE "FCStatus" AS ENUM ('APPROVED', 'DENIED', 'DISCOUNTED_CARE', 'STILL_PENDING');
