import type { AgreementBlock } from "../layout";

/** One entry per department, transcribed verbatim from
 *  .superpowers/sdd/department-responsibilities.md (itself transcribed from the
 *  legacy Airtable director contract). `body` is authored in the markdown
 *  subset from contract/prose.tsx: a blank-line-separated paragraph for the
 *  hours line, then `- ` bullets for the duties.
 *
 *  Names below are the legacy Airtable labels, which intentionally differ from
 *  prisma/department-catalog.ts for a few codes (for example ITCM's catalog
 *  name is "IT & Compliance Management" but the contract shows
 *  "IT and Communications"). Codes are verified against the catalog; names are
 *  not meant to match it. */
type DeptSpec = { code: string; name: string; hours: string; duties: string[] };

const DEPARTMENTS: DeptSpec[] = [
  { code: "BVHD", name: "Behavioral Health", hours: "10", duties: [
    "Supervising volunteers who screen patients during clinic to determine program eligibility.",
    "Working in collaboration with a psychiatrist and a psychologist to oversee the one-on-one psychoeducation offered to enrolled patients.",
    "Training BHD volunteers on the Behavioral Health program curriculum, as well as principles of population health, quality improvement, and motivational interviewing.",
    "Meeting weekly with our faculty advisors to review clinic screening, discuss program content, troubleshoot any issues, and prepare students for future program sessions.",
    "Continuously seeking community resources for patients and expanding behavioral health offerings at {{orgName}}, for example substance use, smoking cessation, and supporting parenting.",
  ] },
  { code: "CRAD", name: "Community Relations and Advocacy", hours: "10", duties: [
    "Serve as co-chair for the Community Relations and Engagement Committee (CREC).",
    "Oversee {{orgName}} projects and initiatives centered around advocacy efforts and community partnerships.",
    "Extensive involvement as one of {{orgName}}'s main representatives in the HUSKY 4 Immigrants Coalition, in collaboration with the Executive Director and Jones Fellow. Establish new relationships with non-profit organizations in the New Haven community.",
    "Maintain existing partnerships with {{orgName}}'s community partners and update the community partners master spreadsheet.",
    "Check in with each community partner at least once a semester in order to stay connected and integrated in the community. Attend community partner meetings at determined frequency.",
    "Seek collaboration events with local non-profit organizations in New Haven and coordinate volunteer involvement for these events.",
    "Serve as part of the planning team and help co-lead {{orgName}}'s community events such as our Annual Flu Clinics. Collaborate with the PR Director to complete an annual report for {{orgName}}'s community partners.",
    "Assess potential for implementing a community advisory board or patient advisory board and spearhead that process. Maintain and continue to build the {{orgName}} resource database and update all information.",
  ] },
  { code: "EDUC", name: "Education", hours: "5-15", duties: [
    "Providing one-on-one health counseling as a part of our motivational interviewing-based program, including scheduling and conducting follow up education as needed.",
    "Organizing training of all volunteers. Training includes a programmatic overview, motivational interviewing session, and general overview of the relevant subject matter. Also may involve collaboration with faculty and experts.",
    "Organizing and interpreting patient history, including previous visits with the Education department, previous medical visits and diagnoses, and relevant laboratory tests.",
    "Ensuring volunteer continuity and review of patient progress metrics.",
    "Continuing to develop culturally appropriate curriculum for each of the counseling programs.",
    "Overseeing the hiring and training of new Education volunteers and creating a volunteer schedule for each semester based on clinic needs and volunteer availability.",
    "Developing new ideas for programs and community outreach through patient needs assessments.",
    "Assisting with current initiatives: getting Education-specific interpreters and equipping our volunteers with more social services skills to better serve our patients.",
    "Overseeing and taking leadership of Education projects such as the healthy recipe cookbook, YouTube playlist, and Health Literacy Project.",
    "Creating and digitally sending monthly Education newsletters to communicate department updates and clinic schedules.",
    "Helping to create budget requests and ordering or transporting budget items.",
    "Planning and hosting social events to foster camaraderie within the department.",
  ] },
  { code: "EXEC", name: "Executive Director", hours: "15-20", duties: [
    "Creating {{orgName}} policies and determining operating procedures with the goal of sustainability and institutional continuity.",
    "Promoting the development of programs and initiatives in line with the mission and vision of {{orgName}} and facilitating the development of quarterly goals for each department.",
    "Meeting weekly with your co-directors. Meeting monthly with {{orgName}}'s Medical Directors.",
    "Conducting board meetings every 2 weeks and Steering Committee meetings every 3 months.",
    "Meeting monthly with the Directors of each department to support departments in their initiatives and ensure follow-up.",
    "Managing clinic and overseeing patient flow as Session Coordinator 1 to 2 Saturdays per month at the Clinic.",
    "Promoting and representing {{orgName}} at various events such as alumni events, volunteer recruitment, press interviews, and conferences.",
    "Promoting board member development and fostering a collaborative working environment on the {{orgName}} Board.",
  ] },
  { code: "FCRL", name: "Faculty Relations", hours: "5-10", duties: [
    "Seeking out new physicians, advanced practice nurses (APRNs) and physician assistants (PAs) who are interested in becoming preceptors at {{orgName}}.",
    "Managing the onboarding process for new attendings, which consists of credentialing, privileging, and applying for federal medical malpractice insurance for non-Yale providers.",
    "Ensuring that the Clinic has 2 to 3 {{orgName}} attendings each week and sending out a weekly reminder email.",
    "Completing and submitting the annual application for federal medical malpractice (FTCA Redeeming application) and the FTCA Supplemental Deeming application for additional preceptors added during the year.",
    "Keeping all documentation for each {{orgName}} attending up to date and organized.",
    "Organizing an annual faculty appreciation Thank You Card-athon.",
    "Send out {{orgName}} attendings feedback survey at the end of the year to obtain faculty feedback and report findings to Executive Co-Directors and Faculty Advisor.",
    "Form and maintain key relationships on behalf of the clinic. Some organizations with which we interact include Fair Haven Community Health Care, Cornell Scott Hill Health Center, Nathan Smith Clinic, Project Access, and YNHH.",
  ] },
  { code: "FIND", name: "Finance and Development", hours: "5-15", duties: [
    "Leading the Sustainability and Development Committee, including spearheading the annual ANDA 5K walk and run in October which is our largest annual fundraiser, Gryphon fundraisers, and the Annual Appeal to solicit donations from {{orgName}} alumni.",
    "Reviewing and approving reimbursements for {{orgName}} related expenses by the leadership board and volunteers.",
    "Creating and managing the annual departmental budget.",
    "Tracking revenues and expenses in each of {{orgName}}'s several major accounts, in collaboration with YSM Finance.",
    "Where applicable, assisting Executive Directors and other {{orgName}} student leaders in applying for grants.",
    "Organizing and updating our fundraising materials.",
    "Facilitating the recruitment of new {{orgName}} donors and managing relationships with current donors, including tracking donations and sending thank you notes.",
  ] },
  { code: "ITCM", name: "IT and Communications", hours: "5-10", duties: [
    "Organizing Epic access for all volunteers and directors with the appropriate level of access and communicating with YNHH to that effect.",
    "Promoting the development of programs and initiatives in line with the mission and vision of {{orgName}} and facilitating the development of quarterly goals.",
    "Attending board meetings every 2 weeks and subcommittee meetings, as well as running IT department meetings.",
    "Supporting and supervising the use of Epic, Microsoft Teams, and other IT software within the clinic.",
    "Working with other board directors and executive directors to identify new projects and initiatives and managing these projects within the department, especially QA/QI, Student Recruitment, and Public Relations.",
    "Maintaining {{orgName}}'s website.",
  ] },
  { code: "INTP", name: "Interpreting and Diversity", hours: "5-10", duties: [
    "Recruiting and managing interpreters of non-Spanish languages, not limited to but including Hindi, Urdu, Arabic, Portuguese and Bengali. Candidates do not need to speak these languages.",
    "Continuing to develop comprehensive training and support programs for interpreting volunteers. This includes managing interpreter schedules and communicating feedback.",
    "Conducting assessments of interpreter applicants' Spanish proficiency to select a core group of high-quality, dedicated interpreters. Collecting feedback from clinical teams on interpreter performance to ensure ongoing high-quality communication with patients.",
    "Coordinating assessments of Spanish ability for all new volunteers for each recruitment period, 3 times annually. Soliciting the help of interpreters or Spanish-speaking Board members to assist in assessments.",
    "Staying informed of issues affecting the health and wellbeing of Latino immigrants and residents of Fair Haven and New Haven, and engaging the leadership of {{orgName}} in opportunities for advocacy. Maintaining all volunteers informed on these issues and culturally competent care.",
    "Participating in board decision-making, new program development, and program evaluation with a focus on diversity and community accountability.",
    "Continuing to work on {{orgName}}'s implicit bias training in collaboration with QA/QI, as well as the clinic's cultural competency training.",
    "Serving as one of the sub-committee leaders for the Community Relations and Engagement Committee, either one of the Directors.",
    "Control quality of translations of after visit summaries.",
  ] },
  { code: "LABR", name: "Laboratory", hours: "8-10", duties: [
    "Coordinating the smooth running of lab from week to week, such as keeping supplies stocked, ensuring quality control and compliance, avoiding lab errors, and handling patient lab bills.",
    "Training and supervising lab volunteers in venipuncture and lab skills, including coordinating venipuncture training with an official phlebotomy trainer and ensuring location, schedule, and date of training each semester.",
    "Working with the IT Director for access to Epic for {{orgName}} volunteers as needed.",
    "Coordinating the scheduling of lab volunteers and supervising volunteers during clinic. Each co-director is expected to oversee the lab for at least half of the number of shifts per term.",
    "Acting as a liaison between YNHH, where lab tests are run, and the clinic.",
  ] },
  { code: "LCCN", name: "Longitudinal Care Coordination", hours: "10-20", duties: [
    "Managing the Care Coordination Program, a program designed to improve navigation and coordination of care for {{orgName}} medically and socially complex patients.",
    "Understanding the needs of the patients while maintaining a high level of respect and confidentiality.",
    "Identifying case management tools and interdisciplinary care plans by organizing meetings and coordinating the information and care requirements.",
    "Complying with {{orgName}}'s mission and requiring adherence to the governing regulations.",
    "Assessing the regular functioning of the program and reporting the evaluation details to the Board and steering committees, for example tracking changes in ED visits, no-show appointments, and patient and provider satisfaction pre and post enrollment.",
    "Managing data and being able to implement strategies to improve the program.",
    "Evaluating the efficacy and efficiency of the program by determining and measuring the appropriate metrics.",
    "Weekly tracking of all Emergency Department visits and follow up care.",
    "Connecting patients with ancillary departments at {{orgName}} or other community-based organizations in New Haven.",
    "Coordinating transfers of care out of {{orgName}} to other FQHCs.",
    "In collaboration with MDIC, enrolling patients in YNHH Financial Assistance Programs.",
    "In collaboration with the Referrals department, coordinating referrals to specialty appointments and helping patients to establish care with specialty providers, ensuring transportation to appointments is secured, and helping to define goals and questions for specialist appointments.",
    "Leading patient navigation and advocacy training.",
    "Ensuring that longitudinal SCTMs are trained in Chronic Disease Management (CDM) curriculum for Diabetes and Hypertension Pathways.",
    "Tracking patients enrolled in the CDM pathways and ensuring that Patient Navigators follow up with CDM progress.",
  ] },
  { code: "MDIC", name: "Medical Debt and Insurance Counseling", hours: "10-15", duties: [
    "Initiate Medicaid Application and YNHH Financial Assistance Program (Free Care) Application processes.",
    "Regularly follow up with YNHH contacts to clarify updates regarding free care status.",
    "Resolve outstanding bills pertaining to YNHH, regardless of department, and Yale Medicine.",
    "Apply guarantor accounts to patients of select departments with potential referrals prior to Saturday clinic days for covering YNHH lab and imaging and certain Yale Medicine bills.",
    "Develop a system and coordinate information for rebilling bills as {{orgName}} bills with YNHH and other appropriate contacts.",
    "Develop a systemic program for addressing bills not affiliated with YNHH.",
    "Create a protocol for handling communications with debt collectors and preserving patient rights.",
    "Develop a communication system with external hospitals for all other bills.",
    "Attend Saturday clinics to lead volunteers and to meet with patients with billing concerns.",
  ] },
  { code: "PATS", name: "Patient Services", hours: "10-20", duties: [
    "Act as Patient Services Director approximately every third Saturday.",
    "Be responsible for the {{orgName}} phone the week prior to your clinic shift, which includes returning phone calls as needed within 24 hours, making phone calls or sending messages via CareMessage during the week to remind patients about their upcoming appointments, and maintaining supplies for the department such as appointment cards kept at the desk.",
    "Facilitating all communication between {{orgName}} and {{orgName}} patients.",
    "Communicate with patients about different {{orgName}} initiatives and help direct them to appropriate resources.",
    "Triaging walk-in patients and performing new patient intakes.",
    "Managing clinic flow and the patient waiting room along with the session coordinator.",
    "Manage the clinic's appointment schedule and maintain organized medical records using Epic.",
    "Scheduling, training, and supervising volunteers who work at the front desk.",
    "Responding to the appointment phone during the week and scheduling any patients who may call.",
    "Clinical phone calls will be triaged with the help of the Department Directors and Clinical Advisors.",
    "Communicating with other departmental directors throughout the week to schedule appointments and coordinate care.",
  ] },
  { code: "PBRL", name: "Public Relations", hours: "5-10", duties: [
    "Support the Sustainability and Development committee with designing materials for the annual 5K and other fundraising efforts.",
    "Maintain {{orgName}}'s social media presence on Facebook, Instagram, LinkedIn, and other social networks.",
    "Work with other board directors and the Executive Directors on various graphic design projects such as flyers, brochures, notices, and clinic decorations.",
    "Develop and distribute the monthly volunteer newsletter.",
    "Build a brand image for the clinic, for example improving the logo and setting a color scheme and font set.",
    "Work with the Office of Alumni Affairs and Development at Yale and others to develop strategies to increase alumni engagement, such as the annual report or creating an annual alumni newsletter.",
    "Support the CREC-Advocacy Committee with providing volunteers with a list of advocacy-related events on campus and in the New Haven community.",
    "Collaborate with the Student Recruitment and Relations Director to reach out to various Yale schools and beyond to recruit volunteers.",
    "Seek ways to promote the clinic, such as writing articles and reaching out to local news sources.",
  ] },
  { code: "PCAR", name: "Clinical Advisor", hours: "15-20", duties: [
    "Leading the training of Senior Clinical Team Members and Junior Clinical Team Members, three sessions per year.",
    "Preparing for all primary care patient visits by reviewing the medical record and preparing a CA Note which provides a brief clinical summary of important tasks for the primary team.",
    "Deciding on clinically appropriate reschedules for patients as needed based on clinic staffing.",
    "Supervise and assist triage SCTM in answering patient phone calls during the week for new medical concerns or medication refills under supervision of the on-call attending.",
    "Order screening labs and imaging prior to patient encounter to ensure compliance with USPSTF guidelines.",
    "Triage walk-in patients.",
    "Reviewing all lab and imaging results and following up with patients appropriately for results, also ensuring all labs ordered are returned.",
    "Supervising a clinical communications Junior Clinical Team Member during Saturday clinic to assist in triage and informing patients of test and imaging results.",
    "Overseeing complex patients that are identified and followed at {{orgName}}.",
    "Working as a Senior Clinical Team Member in times of overflow as needed.",
    "Developing and monitoring standards of patient care, as well as measures to increase efficiency and clinic flow.",
    "Working with the Clinical Quality Assurance committee to develop interdepartmental initiatives to improve patient care.",
    "Consulting with and reviewing charts with the Referrals team to assist in specialty-care related decision making.",
    "Participate in weekly signout with co-CAs to ensure appropriate handoffs.",
  ] },
  { code: "PHAM", name: "Pharmacy", hours: "5-15", duties: [
    "Directors are each expected to be in Clinic every other weekend, or the equivalent. For Pharmacy, Clinic typically runs from 8:00am to 4:00pm, which is 8 or more hours. Non-clinical responsibilities typically take 5 or more hours per week, on average.",
    "Budgeting, sourcing, logging, and maintaining the pharmacy inventory of supplies and medications.",
    "Coordinating pharmacy donation deliveries with Direct Relief, Americares, and the DPH.",
    "Overseeing the pharmacy volunteers, including liaising, scheduling, and training.",
    "Following up with patients and clinical teams to ensure medications are delivered. Coordinating deliveries of medications.",
  ] },
  { code: "QAQI", name: "Quality Assurance and Improvement", hours: "10-15", duties: [
    "Aggregate project recommendations and quality improvement priorities from CQA and department directors to set goals and priorities for QAQI volunteers.",
    "Train QAQI volunteers on tasks and responsibilities, including shadowing clinic departments.",
    "Select, manage, and supervise all volunteers.",
    "Ensure all volunteers have their HIPAA forms completed. Establish and track requirements for volunteers.",
    "Assign and create research projects for each volunteer as necessary.",
    "Allocating workload to volunteers, such that they are adequately engaged but not overwhelmed.",
    "Make volunteers feel supported.",
    "Oversee research at {{orgName}}, including research proposals and ongoing research.",
    "Oversee all ongoing quality improvement projects.",
    "Aid the Jones Fellow in gathering data for the annual alumni and donor report.",
    "Oversee Patient Satisfaction survey implementation and aggregation.",
    "Chair and attend all meetings for the CQA (Committee for Quality Assurance) subcommittee. Participation includes attending meetings, helping to drive and shape strategy of the committee, and participating actively in initiatives of the committee.",
    "Plan and organize the annual Strategic Planning Retreat.",
    "Support the creation of every department's Strategic SMART Goals and serve as accountability.",
    "Support the submission of abstracts from {{orgName}} to the annual Society for Student-Run Free Clinics Conference.",
    "Collect patient tracker and visit data and clinical outcomes data. Support the creation of a Clinical Outcomes and Standard of Care annual report.",
  ] },
  { code: "REFF", name: "Referrals", hours: "10-15", duties: [
    "Oversee the logistics of the various referrals services including referral approval, appointment scheduling, and results follow-up.",
    "Manage volunteers who communicate with patients to confirm specialty appointment dates, provide reminders to ensure attendance, and troubleshoot any patient questions or concerns.",
    "Coordinate with MDIC regarding applications for financial assistance.",
    "Ensure that patients and clinical team members are informed about the details and results of their appointments.",
    "Plan and coordinate specialty screening days in clinic, for example vision, physical therapy, and mammograms, to provide access to high demand services.",
    "Recruit specialist providers for new specialties or when a current provider can no longer work with {{orgName}}, and troubleshoot any issues arising with existing providers.",
  ] },
  { code: "SOSE", name: "Social Services", hours: "10-15", duties: [
    "Scheduling, training and supervising the Social Services volunteers. This includes developing training tools each term, and updating ongoing resource reference materials for volunteers.",
    "Assisting volunteers with documenting patient interactions and formulating an appropriate follow up plan for each patient.",
    "Maintaining an internal Social Services patient needs and quantitative data tracking system, while updating Epic electronic health records.",
    "Building internal Social Services patient trackers by detailing action items for scheduled patient visits, coordinating unscheduled patient encounters with other {{orgName}} departments, and researching personalized resource requests.",
    "Monitoring both tele-health and in-person clinic operations, and virtual patient tracking and follow-up systems.",
    "Following active and urgent patient cases outside of clinic hours. This involves contacting other primary care clinics, social services agencies, and patients. Directors can delegate follow-up to volunteers if sufficiently supervised.",
    "Acting as care coordinators for patients by following up on open interactions with both clinical and ancillary {{orgName}} departments and coordinating with Patient Services to refer and schedule appointments for patients accordingly.",
    "Maintaining updated lists of community resources, cultivating ongoing relationships with community partners, and actively seeking out new resources and contacts for patients. This sometimes requires video conferencing or going off campus during the week, mostly during normal business hours.",
    "Learning about the various federal, state, and community-based programs available for low-income adults, children, and families, and corresponding requirements for eligibility.",
    "There is an expectation that Directors will dedicate time both in and out of clinic to improving the services we offer, in addition to performing their required weekly duties.",
  ] },
  { code: "SRR", name: "Student Recruitment and Relations", hours: "5-10, up to 20 during recruitment", duties: [
    "This position requires you to change your email platform to Outlook, if not already.",
    "Addressing prospective and current volunteer inquiries from the {{orgName}} recruitment email.",
    "Organizing student volunteer and leadership board applications, info sessions, and recruitment events.",
    "Facilitating volunteer and director selection process.",
    "Organizing volunteer contact information and schedules.",
    "Maintain volunteer lists and assist board members with volunteer issues.",
    "Organize and implement volunteer training.",
    "Managing volunteer shift trades, attendance, and concerns.",
    "Sending reminder emails to all volunteers each week.",
    "Managing volunteer feedback and communicating issues with the board as necessary.",
    "Working with IT to maintain up to date training and volunteer records.",
  ] },
  { code: "SRHD", name: "Sexual and Reproductive Health", hours: "10-15", duties: [
    "Overseeing all departmental clinic day workflow logistics and overseeing role execution and providing guidance to clinical members of the team, including SCTMs, JCTMs and RHD Care Coordinators.",
    "Assisting SCTMs in providing reproductive health education, counseling, and resources to {{orgName}} patients. Topics include contraception counseling, STIs, abnormal test or imaging results, hormone therapy for menopause or gender affirming care, pregnancy options, fertility and menopause counseling.",
    "Consulting and coordinating with other {{orgName}} departmental directors if patient care needs lie outside of our department's scope, for example Labs, Medical Billing, Legal Help, and non-sexual and reproductive health concerns.",
    "For non-RHD patients, providing additional counseling and educational resources to patients that consult us for sexual or reproductive health concerns.",
    "Overseeing procedural logistics for IUD and Nexplanon placements.",
    "Monitoring and re-ordering to maintain RHD supply and instrument inventory.",
    "Monitoring clinic-wide pregnancy testing and providing counselling based on patient goals.",
    "Post clinic and during the week: patient follow-up calls as needed, for example counseling, triaging, and refilling medications. May include discussing results and plans of care with attendings and following Epic messaging closely for normal and abnormal results. May include working with ancillary departments.",
    "Pre-clinic and during the week: preparation of clinic patient list and communicating with the volunteer team on duty by mid-week regarding patient assignments. Calling patients for pertinent pre-appointment reminders, either to get pre-appointment labs or to take pain medications if getting a procedure.",
    "Volunteer management, including selection, training, and scheduling.",
    "Reviewing and updating protocols and resources, including maintaining or generating the Reproductive Health Department electronic resources such as Teams resources and patient tracking.",
    "Working closely with the Clinical Advisors, Education, Social Services, and Referrals directors to develop programming and resources to expand and improve reproductive health at {{orgName}}.",
    "Meeting once a month with the Reproductive Health attending and Medical Director.",
  ] },
  { code: "VADM", name: "Vaccine", hours: "5-10", duties: [
    "Organize weekly vaccine administrator and coordinator coverage.",
    "Complete pre-clinic preparation by reviewing appointments, rescheduling as needed, and communicating with clinical team members and EDs.",
    "Regularly check vaccine inventory and order to maintain an adequate supply.",
    "Ensure compliance of records and paperwork in accordance with state (CTWiz) and clinic (Epic) standards.",
    "Work with clinical advisors to update patient medical records and vaccine tracker.",
    "Outreach for new vaccine administrators.",
  ] },
];

export const DEPARTMENT_RESPONSIBILITY_BLOCKS: AgreementBlock[] = DEPARTMENTS.map((d) => ({
  kind: "agreement",
  id: `dept_${d.code.toLowerCase()}`,
  title: `Department-Specific Responsibilities: ${d.name}`,
  confirmKind: "checkbox",
  signatureLabel: "I confirm these responsibilities",
  body: [`Approximate hours per week: ${d.hours}`, "", ...d.duties.map((x) => `- ${x}`)].join("\n"),
  visibleWhen: { field: "department", op: "is", value: d.code },
}));
