import {
  CalendarDays,
  ClipboardList,
  GraduationCap,
  HeartHandshake,
  MessagesSquare,
  Send,
  Settings,
  UserRoundPen,
  Users,
} from "lucide-react";
import type { ModuleManifest } from "./types";

/** The single wiring point for modules (spec §8). Hub tiles render from this. */
export const MODULES: ModuleManifest[] = [
  {
    id: "schedule",
    title: "Clinic Schedule",
    description: "Build and view department schedules, request swaps",
    icon: CalendarDays,
    accessPermission: "schedule.view",
    permissions: [
      "schedule.view",
      "schedule.edit_own_dept",
      "schedule.edit_all",
      "schedule.manage_requests",
    ],
    status: "active",
    nav: [
      { label: "My schedule", href: "/schedule" },
      { label: "Full schedule", href: "/schedule/full" },
      { label: "Builder", href: "/schedule/builder" },
      { label: "Attendings", href: "/schedule/attendings" },
    ],
  },
  {
    id: "my-info",
    title: "My Info",
    description: "Update your contact info and HIPAA compliance",
    icon: UserRoundPen,
    // No accessPermission: My Info is open to any signed-in matched person,
    // including alumni with no current term (spec decision).
    permissions: [],
    status: "active",
    nav: [],
  },
  {
    id: "volunteers",
    title: "Volunteer Management",
    description: "Compliance, rosters, offboarding, Epic requests, disciplinary",
    icon: Users,
    accessPermission: "volunteers.view",
    permissions: [
      "volunteers.view",
      "volunteers.manage_compliance",
      "volunteers.manage_offboarding",
      "volunteers.manage_epic",
      "volunteers.issue_disciplinary",
    ],
    status: "active",
    nav: [
      { label: "Compliance", href: "/volunteers" },
      { label: "Master view", href: "/volunteers/master" },
      { label: "Offboarding", href: "/volunteers/offboarding" },
      { label: "Epic requests", href: "/volunteers/epic" },
      { label: "Disciplinary", href: "/volunteers/disciplinary" },
    ],
  },
  {
    id: "admin",
    title: "Admin",
    description: "People, terms, roles, sync health, audit log",
    icon: Settings,
    accessPermission: "admin.access",
    permissions: [
      "admin.access",
      "admin.manage_people",
      "admin.manage_terms",
      "admin.manage_roles",
      "admin.view_audit",
      "admin.manage_sync",
      "admin.manage_email_templates",
      "admin.send_email_campaign",
      "admin.manage_settings",
      "admin.manage_departments",
    ],
    status: "active",
    nav: [
      { label: "Overview", href: "/admin" },
      { label: "People", href: "/admin/people" },
      { label: "Terms", href: "/admin/terms" },
      { label: "Roles", href: "/admin/roles" },
      { label: "Departments", href: "/admin/departments" },
      { label: "Audit", href: "/admin/audit" },
      { label: "Sync", href: "/admin/sync" },
      { label: "Email", href: "/admin/email" },
      { label: "Settings", href: "/admin/settings" },
      { label: "ITCM", href: "/admin/itcm" },
    ],
  },
  {
    id: "recruitment",
    title: "Recruitment",
    description: "Run recruitment cycles, build applications, review submissions",
    icon: ClipboardList,
    accessPermission: "recruitment.access",
    permissions: ["recruitment.access", "recruitment.manage_cycles", "recruitment.review", "recruitment.review_all"],
    status: "active",
    nav: [{ label: "Cycles", href: "/recruitment" }],
  },
  {
    id: "learning",
    title: "Learning",
    description: "Self-paced training courses assigned by department",
    icon: GraduationCap,
    accessPermission: "learning.access",
    permissions: ["learning.access", "learning.manage_courses", "learning.view_progress"],
    status: "active",
    nav: [
      { label: "My courses", href: "/learning" },
      { label: "Manage courses", href: "/learning/manage" },
      { label: "Completion", href: "/learning/dashboard" },
    ],
  },
  {
    id: "triage",
    title: "Triage",
    description: "Patient case coordination across departments",
    icon: MessagesSquare,
    accessPermission: "triage.access",
    permissions: ["triage.access"],
    status: "coming-soon",
    nav: [],
  },
  {
    id: "referrals",
    title: "Referrals",
    description: "Track outgoing patient referrals",
    icon: Send,
    accessPermission: "referrals.access",
    permissions: ["referrals.access"],
    status: "coming-soon",
    nav: [],
  },
  {
    id: "patient-trackers",
    title: "Patient Trackers",
    description: "Department patient tracking workflows",
    icon: HeartHandshake,
    accessPermission: "patient-trackers.access",
    permissions: ["patient-trackers.access"],
    status: "coming-soon",
    nav: [],
  },
];

export function getModule(id: string): ModuleManifest | undefined {
  return MODULES.find((m) => m.id === id);
}
